### ISSUE TITLE
migrating

### ISSUE THREAD

**Issue by nyck33** [ttlg/riverpod_todo#1]
will you do it?

**Comment by ttlg** [comment]
Sure, I will do it. I am waiting for v1.0.

**Comment by nyck33** [comment]
Awesome blog, I learned a lot.

**Comment by nyck33** [comment]
for future reference for anyone visiting this issue,  to migrate to null safety comment out the dependency override and analyzer below it and follow here: https://dart.dev/null-safety/migration-guide

**Comment by nyck33** [comment]
@ttlg Hi Yota-san, I realized quite a major demerit, imho, of Riverpod and that is that the state is not restored when a user leaves the app and returns.  I used SharedPreferences, like in your blog, to restore the data but wondered in your example app here, do you also restore the Navigator stack so the user comes back to the same screen they were last on?  I asked on Reddit and the answers seem very complicated for something that actually I've been told occurs automatically in Flutter if other libraries like Riverpod are not used: https://www.reddit.com/r/flutterhelp/comments/psdrvf/using_riverpod_and_sharedpreferences_to_return_to/

**Comment by ttlg** [comment]
Navigator is not related to riverpod. 
I think Navigator and Riverpod should be considered separately.
I am using routemaster to handle Navigator things https://pub.dev/packages/routemaster
